strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows2012:
      imageName: 'vs2015-win2012r2'
    windows2016:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)
  demands: npm

steps:
  - script: 'git config --global core.autocrlf input'
    displayName: 'config CRLF'
  - checkout: self
  - task: NodeTool@0
    displayName: 'Use Node 8.x'
    inputs:
      versionSpec: 8.x
  - script: 'npm install'
    displayName: 'install dependencies'
  - script: 'cat testtest.txt'
    displayName: 'cat'
  - script: 'npm run lint'
    displayName: 'lint'
